CREATE OR REPLACE NONEDITIONABLE PACKAGE HEITOR_LIBRARY IS

FUNCTION BISSEXTOX(YEAR IN VARCHAR2)
RETURN VARCHAR2;


FUNCTION CHRONOS(DATA              IN DATE,
                 SKIP_BUSINESS_DAY IN VARCHAR2 DEFAULT 2,
                 SIGN              IN VARCHAR2 DEFAULT 1,
                 DAYS              IN VARCHAR2 DEFAULT NULL)

RETURN DATE;


FUNCTION PASCHALIS_CALCULUS(YEAR         IN VARCHAR2,
                            HOLIDAY_TYPE IN VARCHAR2 DEFAULT NULL,
                            CARNIVAL_DAY IN VARCHAR2 DEFAULT 1)
RETURN DATE;


FUNCTION TEMPUS_DOMINUS(START_DATE    IN DATE,
                        END_DATE      IN DATE,
                        CALENDAR_RULE IN VARCHAR2 DEFAULT 1,
                        FULLINTERVAL  IN VARCHAR2 DEFAULT 1)
RETURN NUMBER;


FUNCTION BINAREON(MESSAGE IN VARCHAR2,
                  ACTION  IN VARCHAR2)
RETURN VARCHAR2;


FUNCTION ACENTLESS(TEXT IN VARCHAR2)
RETURN VARCHAR2;


FUNCTION MORSECODEX(MESSAGE IN VARCHAR2,
                    ACTION  IN VARCHAR2)
RETURN VARCHAR2;


FUNCTION DAMERAU_LEVENSHTEIN(TEXT1 IN VARCHAR2,
                             TEXT2 IN VARCHAR2)
RETURN NUMBER;


FUNCTION DOCFORMAT(DOCNUMBER IN VARCHAR2,
                   ACTION    IN VARCHAR2)
RETURN VARCHAR2;


FUNCTION VALIDUSDOC(NUMDOC  IN VARCHAR2,
                    TIPODOC IN VARCHAR2)
RETURN VARCHAR2;


FUNCTION CREATED_COMPLIANT_DOC(TIPODOC IN VARCHAR2,
                               ACTION  IN VARCHAR2 DEFAULT 2)
RETURN VARCHAR2;


FUNCTION CRYPTIFY(TEXT   IN VARCHAR2,
                  KEY    IN VARCHAR2,
                  ACTION IN VARCHAR2)
RETURN VARCHAR2;


FUNCTION IMPERIUMWORDS(VALUE IN VARCHAR2,
                       UNIT  IN VARCHAR2 DEFAULT 1)
RETURN VARCHAR2;


FUNCTION LUHN_VALIDATOR(CARD IN VARCHAR2)

RETURN VARCHAR2;


FUNCTION LUHN_CREATOR(BAND IN VARCHAR2)

RETURN VARCHAR2;


FUNCTION FIBONACCI_SERIE(POS IN VARCHAR2)

RETURN SYS.ODCINUMBERLIST;


FUNCTION GENPASS(RANGE IN VARCHAR2 DEFAULT 10)

RETURN VARCHAR2;


FUNCTION HUMAN_DELTA(START_DATE IN DATE,
                     END_DATE   IN DATE DEFAULT SYSDATE)

RETURN VARCHAR2;


FUNCTION PRIMARY_TARGET(NUM IN VARCHAR2)

RETURN VARCHAR2;


FUNCTION CALCULUS_HORARIUM(START_DATE       IN DATE,
                           END_DATE         IN DATE,
                           ENTRY_TIME       IN VARCHAR2,
                           EXIT_TIME        IN VARCHAR2,
                           LUNCH_START_TIME IN VARCHAR2,
                           LUNCH_END_TIME   IN VARCHAR2,
                           CALENDAR_ROLL    IN VARCHAR2 DEFAULT 1)
RETURN NUMBER;

END;